version: '3.0'
services:
    samba:
        image: dperson/samba
        ports:
            - "137:137/udp"
            - "138:138/udp"
            - "139:139/tcp"
            - "445:445/tcp"
        volumes:
            - ./data:/mnt

